### ISSUE TITLE
Docker compose support?

### ISSUE THREAD

**Issue by marcusit** [MicrosoftDocs/CloudAppSecurityDocs#46]
Have anyone had any luck getting this running using Docker Compose versus Docker run?
I was able to translate most of the run command into a compose file, but is stuck at the "echo &lt;key&gt; | starter" part. (compose file WIP below)

Looking at the shell script "starter" (/etc/adallom/scripts/starter) if we could check if the TOKEN variable exists as an environmental variable then we could pass this token by using an environment option in our Docker Compose script (or as a " -e 'TOKEN=xxxxx' " flag in the Docker run command).

Right now the only way I got it working is by logging in to the container and running "starter &lt;&lt;&lt; &lt;key&gt;" which is not optimal as it has to be re-run each time the container is rebuilt.

---------------------------------------------------------------------
/etc/adallom/scripts/starter (Before)
---------------------------------------------------------------------
#!/bin/bash
first_run() {
    echo "Setting environment"
    read TOKEN

---------------------------------------------------------------------
/etc/adallom/scripts/starter (Suggested)
---------------------------------------------------------------------
#!/bin/bash
first_run() {
    echo "Setting environment"
    if [ -z "$TOKEN" ]
    then
        read TOKEN
    fi

---------------------------------------------------------------------
Docker Compose File
---------------------------------------------------------------------
version: '3.5'
services:
  caslogcollector:
    image: microsoft/caslogcollector:latest
    container_name: Log-Collector
    restart: always
    ports:
      - '21:21'
      - '601:601/tcp'
      - '20000-20099:20000-20099'
    environment:
      - PUBLICIP=xx.xx.xx.xx
      - PROXY=
      - SYSLOG=true
      - CONSOLE=xxxxxx.us2.portal.cloudappsecurity.com
      - COLLECTOR=Log-Collector
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload for continuous reports](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by marcusit** [comment]
I modified the "starter" bash script, rebuilt the container image and was able to pass my token as a variable, allowing for a non interactive deployment of the container.

Steps:
1. Docker run command from step 2.5 in the guide above.
2. docker exec -ti Log-Collector /bin/bash
3. vim /etc/adallom/scripts/starter
4. Replace first few lines with:
#!/bin/bash
first_run() {
    echo "Setting environment"
if [ -z $TOKEN ]; then
    read TOKEN
fi

5. exit
6. docker commit Log-Collector microsoft/caslogcollector:latest-modified
7. docker-compose -f docker-compose.yml up

------------------------------------
Docker Compose File (docker-compose.yml)
------------------------------------
version: '3.5'
services:
  caslogcollector:
    image: microsoft/caslogcollector:latest-modified
    container_name: Log-Collector
    restart: always
    ports:
      - '21:21'
      - '601:601/tcp'
      - '514-515:514-515/udp'
      - '20000-20099:20000-20099'
    environment:
      - PUBLICIP=xxx.xxx.xxx.xxx
      - PROXY=
      - SYSLOG=true
      - CONSOLE=xxxxxxx.us2.portal.cloudappsecurity.com
      - COLLECTOR=Log-Collector
      - TOKEN=xxxxxxxx
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true

**Comment by rkarlin** [comment]
thanks @marcusit ! I've passed this off to our dev team to see if there's something they want to update.

**Comment by mromp** [comment]
In case anyone stumbles across this in the future, the following docker-compose.yml works without having to rebuild the image. This keeps the solution within the spirit of Docker containers remaining ephemeral so that they continue to work when the image is updated or re-built while still keeping secrets somewhat protected.

## Docker Compose File (docker-compose.yml)
```
services:
  mcas:
    image: mcr.microsoft.com/mcas/logcollector:latest
    container_name: mcas
    restart: unless-stopped
    ports:
      - 2121:21
      - 6514:601
      - 20000-20099:20000-20099
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./.secrets/certs:/etc/ssl/private:ro
      - ./.secrets/default_ftppass:/etc/adallom/config/default_ftppass:ro
      - ./.secrets/api_key:/root/api_key:ro
      - ./logs/pure-ftpd:/var/log/pure-ftpd
      - ./logs/syslog.debug:/var/log/syslog.debug
      - ./logs/supervisor:/var/log/supervisor
      - ./logs/adallom:/var/log/adallom
    environment:
      - TZ=America/Chicago
      - PUBLICIP=mcas-hq.ad.skybirch.com
      - SYSLOG=true
      - INCLUDE_TLS=on
      - CONSOLE=skybirch.us3.portal.cloudappsecurity.com
      - COLLECTOR=MCAS-HQ
      - FTPUSER=mcas
    command: /bin/bash -c "cat /root/api_key | /etc/adallom/scripts/starter"
```

Note that this config omits the security_opt and cap_add elements which are not needed and are not a good Docker security practice. 

It also allows for setting a custom FTP username and password, brings in the necessary TLS certificates from the host, and saves the log files outside the container. As with all docker volume mapping, the requisite files and folders need to be added on the host beforehand including the **ca.pem**, **server-cert.pem**, **server-key.pem**, and **pure-ftpd.pem** files in **./.secrets/certs**. Also, be sure your .gitignore file is set to exclude .secrets/ and logs/ from the repo.

On a final note, the API key can also be brought in by pulling out `/etc/adallom/config/columbusUser.cfg` from a working image and mapping it via the volumes element which precludes the need to override the container's default command.
